env:
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    'no-unused-vars': 0,
    'no-constant-condition': 0,
    'no-trailing-spaces': 0,
    'import/no-duplicates': 0,
    'class-methods-use-this': 0,
    'no-useless-return': 0,
    'spaced-comment': 0,
    'import/no-anonymous-default-export': 0,
    'no-empty': 0,
  }
